-- Enable PostGIS extension for geolocation capabilities
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. Organizations (e.g., CIOPS Batalhones, Security Companies)
CREATE TABLE organizations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. User Profiles (Operators, Citizens, Drivers)
CREATE TYPE user_role AS ENUM ('operator', 'citizen', 'driver');

CREATE TABLE profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    role user_role NOT NULL DEFAULT 'citizen',
    full_name TEXT,
    phone_number TEXT,
    organization_id UUID REFERENCES organizations(id), -- Nullable for regular citizens
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Incidents (The SOS Alerts)
CREATE TYPE incident_status AS ENUM ('active', 'acknowledged', 'resolved', 'false_alarm');

CREATE TABLE incidents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
    status incident_status NOT NULL DEFAULT 'active',
    is_hostage_mode BOOLEAN DEFAULT FALSE,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    resolved_at TIMESTAMPTZ,
    resolved_by UUID REFERENCES profiles(id) -- The operator who resolved it
);

-- 4. Telemetry (Location Tracker)
-- Optimized for high frequency inserts
CREATE TABLE telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    incident_id UUID NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    location GEOGRAPHY(POINT) NOT NULL, -- To store Lat/Lng accurately
    battery_level SMALLINT CHECK (battery_level >= 0 AND battery_level <= 100),
    speed_kmh REAL,
    recorded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast spatial queries
CREATE INDEX telemetry_location_gix ON telemetry USING GIST (location);
CREATE INDEX telemetry_incident_id_idx ON telemetry(incident_id);

-- 5. Media Evidence (Photos, Audio logs)
CREATE TABLE incident_media (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    incident_id UUID NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL, -- 'audio/mp4', 'image/jpeg', etc.
    captured_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ==========================================

ALTER TABLE organizations ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE incident_media ENABLE ROW LEVEL SECURITY;

-- Profiles: Users can see their own profile. Operators can see everyone in their organization (or all).
CREATE POLICY "Users can read own profile" ON profiles
    FOR SELECT USING (auth.uid() = id);

-- Assuming 'operator' can see everyone for now (simplified)
CREATE POLICY "Operators can read all profiles" ON profiles
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );

-- Incidents: Users can insert their own incidents, Operators can read/update all incidents
CREATE POLICY "Users can insert own incidents" ON incidents
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can read own active incidents" ON incidents
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Operators can read all incidents" ON incidents
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );

CREATE POLICY "Operators can update incidents" ON incidents
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );

-- Telemetry: Users can insert telemetry for their own active incidents
CREATE POLICY "Users can insert telemetry" ON telemetry
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM incidents i WHERE i.id = incident_id AND i.user_id = auth.uid()
        )
    );

CREATE POLICY "Operators can read telemetry" ON telemetry
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );

-- Media: Users can insert media, Operators can read
CREATE POLICY "Users can insert incident_media" ON incident_media
    FOR INSERT WITH CHECK (
        EXISTS (
            SELECT 1 FROM incidents i WHERE i.id = incident_id AND i.user_id = auth.uid()
        )
    );

CREATE POLICY "Operators can read incident_media" ON incident_media
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );

-- Setup Storage Bucket for Incident Evidence
INSERT INTO storage.buckets (id, name, public) 
VALUES ('evidence', 'evidence', false) ON CONFLICT DO NOTHING;

-- Prevent access to storage for unauthenticated users
CREATE POLICY "Users can upload evidence" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'evidence' AND auth.uid() IS NOT NULL);

CREATE POLICY "Operators can view evidence" ON storage.objects
    FOR SELECT USING (
        bucket_id = 'evidence' AND
        EXISTS (
            SELECT 1 FROM profiles p WHERE p.id = auth.uid() AND p.role = 'operator'
        )
    );
